#!/bin/sh
# ═══════════════════════════════════════════════════════════════════
# CoApis Entrypoint Script
# 容器层准备 + 运行时依赖安装 + 首次启动初始化 + 启动服务器
#
# 职责划分：
#   - entrypoint.sh：容器层准备（版本文件、运行时包、浏览器、MCP 包）
#   - coapis init：应用层初始化（目录、配置、权限、用户）
#   - _app.py lifespan：日常重启增量检查（ensure_ready）
# ═══════════════════════════════════════════════════════════════════
set -e

WORKING_DIR="${COAPIS_WORKING_DIR:-/opt/coapis}"
SYSTEM_DIR="${WORKING_DIR}/system"
COAPIS_VER="${COAPIS_VERSION:-0.0.0-dev}"

echo "=========================================="
echo "CoApis Server Starting"
echo "=========================================="
echo "WORKING_DIR : ${WORKING_DIR}"
echo "IMAGE VARIANT: ${COAPIS_IMAGE_VARIANT:-full}"
echo "VERSION      : ${COAPIS_VER}"
echo "=========================================="

# ── 1. 生成版本文件（从 COAPIS_VERSION 环境变量） ──────────────
cat > /app/coapis/__version__.py << VEOF
# Auto-generated by entrypoint.sh — do not edit manually
# Source: COAPIS_VERSION env var
__version__ = "${COAPIS_VER}"
VEOF
echo "✓ Version file generated."

# ── 2. min 镜像：运行时安装渠道包（挂载 volume，重启不丢失） ───
if [ "${COAPIS_IMAGE_VARIANT}" = "min" ]; then
    RUNTIME_SITE="${WORKING_DIR}/.pip-runtime"
    RUNTIME_MARKER="${RUNTIME_SITE}/.installed"

    if [ ! -f "${RUNTIME_MARKER}" ]; then
        echo ""
        echo "📦 [min image] Installing runtime dependencies to volume..."
        echo "   Target: ${RUNTIME_SITE}"
        echo "   (This only runs once; packages persist across restarts)"
        echo ""

        mkdir -p "${RUNTIME_SITE}"

        # 渠道 SDK（纯 Python，可安全运行时安装）
        RUNTIME_PKGS=""
        # 检查环境变量决定安装哪些渠道包
        if [ -n "${COAPIS_CHANNELS}" ]; then
            case "${COAPIS_CHANNELS}" in
                *feishu*)  RUNTIME_PKGS="${RUNTIME_PKGS} lark-oapi" ;;
            esac
            case "${COAPIS_CHANNELS}" in
                *dingtalk*) RUNTIME_PKGS="${RUNTIME_PKGS} alibabacloud-dingtalk" ;;
            esac
            case "${COAPIS_CHANNELS}" in
                *twilio*|*whatsapp*) RUNTIME_PKGS="${RUNTIME_PKGS} twilio" ;;
            esac
        fi

        # 如果没指定 COAPIS_CHANNELS，默认装所有渠道（安全保守）
        if [ -z "${RUNTIME_PKGS}" ]; then
            RUNTIME_PKGS="lark-oapi alibabacloud-dingtalk twilio"
        fi

        # 可选：中文分词
        case "${COAPIS_OPTIONAL:-}" in
            *jieba*) RUNTIME_PKGS="${RUNTIME_PKGS} jieba" ;;
        esac

        # 执行安装
        if [ -n "${RUNTIME_PKGS}" ]; then
            pip install --target="${RUNTIME_SITE}" --no-cache-dir ${RUNTIME_PKGS}
            echo ""
            echo "✅ Runtime packages installed:${RUNTIME_PKGS}"
        fi

        touch "${RUNTIME_MARKER}"
    else
        echo "✓ Runtime dependencies already installed."
    fi

    # 确保 Python 能找到 volume 中的包
    export PYTHONPATH="${RUNTIME_SITE}:${PYTHONPATH:-}"
    echo "✓ PYTHONPATH updated: ${RUNTIME_SITE} added."
fi

# ── 3. 首次启动初始化（config.json 不存在时） ──────────────────
if [ ! -f "${SYSTEM_DIR}/config.json" ]; then
    echo ""
    echo "📦 First startup detected, running initialization..."
    INIT_ARGS="--defaults --accept-security"
    if [ "${COAPIS_SKIP_PROVIDERS}" = "1" ]; then
        INIT_ARGS="${INIT_ARGS} --skip-providers"
    fi
    coapis init ${INIT_ARGS}
    echo "✅ Initialization complete!"
else
    echo "✓ System already initialized."
fi

# ── 4. 设置 Playwright 浏览器路径 ─────────────────────────────
export PLAYWRIGHT_BROWSERS_PATH=/app/volume/playwright

# ── 5. 安装浏览器自动化（可选） ──────────────────────────────
if [ "${COAPIS_INSTALL_BROWSER}" = "1" ]; then
    if ! playwright --version > /dev/null 2>&1; then
        echo ""
        echo "🌐 Installing browser automation dependencies..."
        pip install --no-cache-dir playwright
        playwright install-deps chromium
        playwright install chromium
        echo "✅ Browser dependencies installed!"
    else
        echo "✓ Browser automation already installed."
    fi
else
    if playwright --version > /dev/null 2>&1; then
        echo "✓ Browser automation available."
    else
        echo "ℹ️  Browser not installed. Set COAPIS_INSTALL_BROWSER=1 to enable."
    fi
fi

# ── 6. 恢复 MCP 包（从 volume 持久化目录） ──────────────────
MCP_VOLUME="/app/volume/mcp"
MCP_TARGET="/usr/local/lib/python3.11/site-packages/mcp"
if [ -d "${MCP_VOLUME}" ] && [ "$(ls -A ${MCP_VOLUME}/*.whl 2>/dev/null)" ]; then
    echo ""
    echo "📦 Restoring MCP packages from volume..."
    for whl in "${MCP_VOLUME}"/*.whl; do
        [ -f "$whl" ] || continue
        pip install --no-cache-dir "$whl" 2>/dev/null || true
    done
    echo "✅ MCP packages restored."
fi

# ── 7. 启动服务器 ────────────────────────────────────────────
echo ""
echo "=========================================="
echo "🚀 Starting CoApis Server..."
echo "=========================================="
exec uvicorn coapis.app._app:app --host 0.0.0.0 --port 8000
