#!/bin/sh
# ═══════════════════════════════════════════════════════════════════
# CoApis Entrypoint Script
# 容器层准备 + 首次启动初始化 + 启动服务器
#
# 职责划分：
#   - entrypoint.sh：容器层准备（版本文件、浏览器、MCP 包）
#   - coapis init：应用层初始化（目录、配置、权限、用户）
#   - _app.py lifespan：日常重启增量检查（ensure_ready）
# ═══════════════════════════════════════════════════════════════════
set -e

WORKING_DIR="${COAPIS_WORKING_DIR:-/opt/coapis}"
SYSTEM_DIR="${WORKING_DIR}/system"

echo "=========================================="
echo "CoApis Server Starting"
echo "=========================================="
echo "WORKING_DIR: ${WORKING_DIR}"
echo "=========================================="

# ── 1. 生成版本文件（从 COAPIS_VERSION 环境变量） ──────────────
COAPIS_VER="${COAPIS_VERSION:-0.0.0-dev}"
cat > /app/coapis/__version__.py << VEOF
# Auto-generated by entrypoint.sh — do not edit manually
# Source: COAPIS_VERSION env var
__version__ = "${COAPIS_VER}"
VEOF
echo "✓ Version: ${COAPIS_VER}"

# ── 2. 首次启动初始化（config.json 不存在时） ──────────────────
# 统一走 coapis init，由 SystemInitializer 处理目录/配置/权限/用户
if [ ! -f "${SYSTEM_DIR}/config.json" ]; then
    echo "📦 First startup detected, running initialization..."
    coapis init --defaults --accept-security
    echo "✅ Initialization complete!"
else
    echo "✓ System already initialized."
fi

# ── 3. 设置 Playwright 浏览器路径 ─────────────────────────────
export PLAYWRIGHT_BROWSERS_PATH=/app/volume/playwright

# ── 4. 安装浏览器自动化（可选） ──────────────────────────────
if [ "${COAPIS_INSTALL_BROWSER}" = "1" ]; then
    if ! playwright --version > /dev/null 2>&1; then
        echo ""
        echo "🌐 Installing browser automation dependencies..."
        pip install --no-cache-dir playwright
        playwright install-deps chromium
        playwright install chromium
        echo "✅ Browser dependencies installed!"
    else
        echo "✓ Browser automation already installed."
    fi
else
    if playwright --version > /dev/null 2>&1; then
        echo "✓ Browser automation available."
    else
        echo "ℹ️  Browser not installed. Set COAPIS_INSTALL_BROWSER=1 to enable."
    fi
fi

# ── 5. 恢复 MCP 包（从 mcp_installed.json 记录） ─────────────
echo ""
echo "Checking MCP package installations..."
python3 -c "
import json, subprocess, os, glob

working_dir = os.environ.get('COAPIS_WORKING_DIR', '/opt/coapis')
patterns = [
    os.path.join(working_dir, 'workspaces/*/mcp_installed.json'),
]
installed_pip = set()
installed_npm = set()

for pattern in patterns:
    for fp in glob.glob(pattern):
        try:
            with open(fp) as f:
                record = json.load(f)
            installed_pip.update(record.get('pip', []))
            installed_npm.update(record.get('npm', []))
        except Exception:
            pass

if installed_pip or installed_npm:
    print(f'  Found {len(installed_pip)} pip + {len(installed_npm)} npm packages to restore')
    for pkg in installed_pip:
        try:
            module = pkg.replace('-', '_').split('[')[0]
            r = subprocess.run(['python3', '-c', f'import {module}'],
                             capture_output=True, timeout=10)
            if r.returncode != 0:
                print(f'  Installing pip: {pkg}')
                subprocess.run(['pip', 'install', '--no-cache-dir', '-q', pkg],
                             capture_output=True, timeout=120)
        except Exception as e:
            print(f'  Warning: failed to install {pkg}: {e}')
    for pkg in installed_npm:
        try:
            print(f'  Installing npm: {pkg}')
            subprocess.run(['npm', 'install', '-g', pkg],
                         capture_output=True, timeout=120)
        except Exception as e:
            print(f'  Warning: failed to install {pkg}: {e}')
else:
    print('  No MCP packages to restore')
" 2>&1

# ── 6. 启动服务器（初始化由 _app.py lifespan ensure_ready 负责） ──
echo ""
echo "🚀 Starting CoApis backend on port ${COAPIS_PORT:-8000}..."
exec uvicorn coapis.app._app:app --host 0.0.0.0 --port "${COAPIS_PORT:-8000}"
